### ISSUE TITLE
Math Processing Error

### ISSUE THREAD

**Issue by 2016rshah** [chris-taylor/chris-taylor.github.io#1]
I was looking at [this post](http://chris-taylor.github.io/blog/2013/02/13/the-algebra-of-algebraic-data-types-part-iii/) and there were a ton of `Math Processing Error`s that you may want to look into

**Comment by chris-taylor** [comment]
This is normally caused by a browser caching issue - doing a hard refresh (Shift + Refresh) solves it. For example, see here -

http://meta.math.stackexchange.com/questions/3627/why-is-math-processing-error-all-over-the-place-today
